development:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_development
  pool: 5
  host: localhost
  username:  Ducky
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_test
  pool: 5
  host: localhost
  username: Ducky
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_production
  pool: 5
  username: Ducky
  password:
